Data manupulation

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     --------------------------------- ------ 51.2/60.8 kB ? eta -:--:--
     ---------------------------------------- 60.8/60.8 kB 1.1 MB/s eta 0:00:00
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.6 MB 2.6 MB/s eta 0:00:05
    --------------------------------------- 0.2/12.6 MB 2.4 MB/s eta 0:00:06
   - -------------------------------------- 0.3/12.6 MB 2.6 MB/s eta 0:00:05
   - -------------------------------------- 0.5/12.6 MB 2.6 MB/s eta 0:00:05
   - -------------------------------------- 0.6/12.6 MB 2.7 MB/s eta 0:00:05
   -- ------------------------------------- 0.7/12.6 MB 2.7 MB/s eta 0:00:05
   -- ------------------------------------- 0.8/12.6 MB 2.6 MB/s eta 0:00:05
   --- ------------------------------------ 1.0/12.6 MB 2.6 MB/s eta 0:00:05
   --- ----


[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [70]:
pip install pillow

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   - -------------------------------------- 0.1/2.6 MB 3.3 MB/s eta 0:00:01
   --- ------------------------------------ 0.2/2.6 MB 2.8 MB/s eta 0:00:01
   ---- ----------------------------------- 0.3/2.6 MB 2.2 MB/s eta 0:00:02
   ----- ---------------------------------- 0.3/2.6 MB 2.1 MB/s eta 0:00:02
   ------ --------------------------------- 0.4/2.6 MB 2.0 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.6 MB 2.1 MB/s eta 0:00:01
   ---------- ----------------------------- 0.7/2.6 MB 2.1 MB/s eta 0:00:01
   ------------ --------------------------- 0.8/2.6 MB 2.2 MB/s eta 0:00:01
   ------------- -------------------------- 0.9/2.6 MB 2.3 MB/s eta 0:00:01
   -------------- ------------------------- 1.0/2.6 MB 2.2 MB/s eta 0:00:01
   --------------- ------------------------ 1.0/2.6 MB 2.1 MB/s eta 0:00:01
   --------------


[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np


In [5]:
l1 = np.array(['1','2',3])
print(l1)

['1' '2' '3']


In [10]:
l2 = np.array([True,False,1])
# l2
print(l2)

[1 0 1]


In [12]:
l3 = np.array([1,2,3])
l = l3.tolist()
print(l)
print(type(l))

[1, 2, 3]
<class 'list'>


In [21]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print()
print(arr)
print()
print(arr[:3,1:])

(3, 3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2 3]
 [5 6]
 [8 9]]


In [31]:
x= [[1,2,3],[4,5,6],[7,8,9]]
print()

In [49]:
arr = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]

l = [6,7,8,9]

if l in arr:
    print(True)
else:
    print(False)

0


In [56]:
arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])
 
print("Given array:")
print(arr)
 
print("\nRemove all rows containing NaN values:")
cleaned_arr = arr[~np.isnan(arr).any(axis=1)]
print(cleaned_arr)

Given array:
[[10.5 22.5  3.8]
 [41.   nan  nan]]

Remove all rows containing NaN values:
[[10.5 22.5  3.8]]


In [52]:
arr = [[1,2,3,4,5],[6,7,8,4,5],[11,12,13,4,5],[16,17,18,19,20]]

l = [9,4]

count = 1
for arr in l:
    count = count+1
print(count)

3


In [68]:
#trim the leading or trailing values 
a = np.array([0,0,0,1,5,65,0,1,2,5,0,0,0])

  
# without trim parameter 
# returns an array without leading and trailing zeros  
  
res = np.trim_zeros(a) 
res1 = np.trim_zeros(a,'f') 
res2 = np.trim_zeros(a,'b') 
print(res) 
print(res1) 
print(res2) 

[ 1  5 65  0  1  2  5]
[ 1  5 65  0  1  2  5  0  0  0]
[ 0  0  0  1  5 65  0  1  2  5]


In [71]:
from PIL import Image

In [ ]:
img = Image.open('sample.png')
img_arr = np.array(img)
# img.show()
print(img_arr)

In [75]:
arr = np.array([1, 2, 3, 6, 7, 8, 4])
mask = arr > 5
print("Mask:", mask)
filtered_arr = arr[mask]
print("Filtered Array:", filtered_arr)

Mask: [False False False  True  True  True False]
Filtered Array: [6 7 8]


In [76]:
arr_2d = np.array([[1, 2, 3],
                   [6, 7, 8],
                   [4, 5, 6]])

# Create a boolean mask for elements greater than 5
mask_2d = arr_2d > 5
print("Mask for 2D array:\n", mask_2d)


Mask for 2D array:
 [[False False False]
 [ True  True  True]
 [False False  True]]


In [77]:
# Create a mask based on the sum of rows
row_sums = arr_2d.sum(axis=1)
row_mask = row_sums > 10
print("Row Mask:", row_mask)


Row Mask: [False  True  True]


In [13]:
# reverse a num array
# arr = np.array([1, 2, 3, 6, 7, 8, 4])
arr = np.array([[1, 2, 3],[6, 7, 8],[4, 5, 6]])
# print(arr[::-1])
# print()
# r = np.flip(arr)
# print(r)
s = arr[:, ::-1]
print(s)

[[3 2 1]
 [8 7 6]
 [6 5 4]]


In [36]:
# read only
arr = np.array([1, 2, 3, 6, 7, 8, 4])
arr.setflags(write=True)
print(arr)

[1 2 3 6 7 8 4]


In [21]:
arr[0]=77
print(arr)

ValueError: assignment destination is read-only

In [26]:
arr1 = np.array([2])
arr1[1] =1
np.insert(arr1,1,10)
arr1

IndexError: index 1 is out of bounds for axis 0 with size 1

In [33]:
arr2 = np.array([])
a = np.append(arr2,1)
print(a)
type(a)
if a == arr2:
    print(True)
else:
    print(False)

[1.]


ValueError: The truth value of an empty array is ambiguous. Use `array.size > 0` to check that an array is not empty.

In [ ]:
import numpy as np

# Create an empty 1D array
arr = np.array([])

# Append an element to the empty array
arr = np.append(arr, 10)

print(arr)


In [34]:
import numpy as np

# Create an empty 1D array
arr = np.array([])

# Append an element and assign it back to arr
arr = np.append(arr, 10)

# Print the updated array
print(arr)  # This will print: [10.]


[10.]


In [39]:
# replace the numpy array elements that doesnt satisfy the given condition
arr3 = np.array([1, 2, 3, -1])
arr3[arr3 < 0] = 0
arr3

array([1, 2, 3, 0])

In [46]:
arr3 = np.array([1, 2, 3, -1])
index = np.where(arr3 == arr3[arr3 < 0])
print(index)


(array([3]),)


In [70]:
arr4 = np.array([ [1.3,2.5,3.6,np.nan], [2.6,3.3,np.nan,5.5],[2.1,3.2,5.4,6.5] ])
rep = np.nanmean(arr4,axis=0)
print(rep)
inds = np.isnan(arr4)
print(inds)
arr4[inds] = np.take(rep, np.where(inds)[1])
print(arr4)


[2.  3.  4.5 6. ]
[[False False False  True]
 [False False  True False]
 [False False False False]]
[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


In [66]:
arr = np.array([[1.3, 2.5, 3.6, np.nan],
                [2.6, 3.3, np.nan, 5.5]])

# Calculate the column-wise mean, ignoring NaNs
col_means = np.nanmean(arr, axis=0)

# Find indices where NaN values are present
inds = np.isnan(arr)

# Replace NaNs with the column means
arr[inds] = np.take(col_means, np.where(inds)[1])

print(arr)

[[1.3 2.5 3.6 5.5]
 [2.6 3.3 3.6 5.5]]


In [72]:
a = 2
while(a > -100):  
    a = a - 1  
    print(a)  

NameError: name 'count' is not defined