In [1]:
#NUMPY

import numpy as np

In [2]:
l1=[1,2,3]
l2=[4,5,6]

print(l1+l2)

[1, 2, 3, 4, 5, 6]


In [6]:
n1 = np.array(l1)
print(n1)
n2 = np.array(l2)
print(n2)
print(n1+n2)

[1 2 3]
[4 5 6]
[5 7 9]


In [9]:
l=[1,2,3,4,'a']
arr=np.array(l)
print(arr)

['1' '2' '3' '4' 'a']


In [11]:
l=[1,2,3,4,3.14,'a']
arr=np.array(l)
print(arr)

['1' '2' '3' '4' '3.14' 'a']


In [29]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [56]:
n = np.array(my_matrix) #change  array
print(n.shape)
print(n)
print(n[1:,1:1])

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[]


In [30]:
n.tolist() #change array to list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [31]:
#built in methods

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [40]:
np.zeros(3)

array([0., 0., 0.])

In [41]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.ones(3)

array([1., 1., 1.])

In [92]:
n = np.zeros((5,5))
np.eye(4)
print(n)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [45]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [49]:
np.random.rand(5,5)

array([[0.16224511, 0.38932099, 0.60019334, 0.80672644, 0.60378548],
       [0.33700976, 0.93234256, 0.63796449, 0.76402049, 0.9854086 ],
       [0.92516989, 0.24254565, 0.03037121, 0.23023033, 0.08022705],
       [0.33893875, 0.84888232, 0.57720748, 0.91029591, 0.12442282],
       [0.99644209, 0.58150987, 0.40711603, 0.7568985 , 0.64486639]])

In [48]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
np.random.randint(1,100, size=(5,5))

array([[39, 74, 84, 17, 37],
       [83, 72, 63, 62, 78],
       [12, 23, 29, 24, 45],
       [67, 72, 63, 57, 37],
       [11,  2, 28, 43, 50]], dtype=int32)

In [57]:
arr_2d =np.array(([1,2,3],[4,5,6],[7,8,9]))
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
print(arr_2d[1])

[4 5 6]


In [59]:
print(arr_2d[1][0])

4


In [61]:
x1= np.random.randint(10, size=6) #one d
print(x1)


[2 0 3 2 7 7]


In [63]:
x2= np.random.randint(10, size=(3,4)) # 2d
print(x2)

[[7 7 2 0]
 [2 4 0 4]
 [0 4 2 4]]


In [64]:
x3= np.random.randint(10, size=(3,4,5)) #3d
print(x3)

[[[7 2 6 1 5]
  [9 9 3 6 8]
  [1 8 6 0 1]
  [4 6 5 6 3]]

 [[9 6 6 0 0]
  [8 5 7 5 1]
  [4 8 2 3 7]
  [3 4 1 9 0]]

 [[2 3 5 4 6]
  [1 8 2 3 1]
  [0 4 7 4 0]
  [9 6 0 3 3]]]


In [65]:
x4= np.random.randint(10, size=(2,3,4,5)) #4d
print(x4)

[[[[2 0 7 4 7]
   [4 2 4 2 0]
   [7 7 1 1 2]
   [4 6 9 4 9]]

  [[6 9 5 6 9]
   [3 6 0 5 7]
   [7 9 7 3 0]
   [1 0 5 4 5]]

  [[8 5 9 9 4]
   [3 7 6 0 4]
   [0 8 9 5 7]
   [0 5 2 1 5]]]


 [[[2 3 3 1 0]
   [3 3 2 0 7]
   [2 3 2 0 1]
   [0 9 6 5 9]]

  [[6 0 9 0 0]
   [8 0 5 2 5]
   [7 0 3 4 2]
   [7 0 7 0 4]]

  [[9 5 0 1 6]
   [2 6 5 8 9]
   [6 6 6 7 0]
   [4 4 5 7 0]]]]


In [68]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

result = np.concatenate([grid, grid])
print(result)


[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [69]:
a = np.array([1,2,3,4,5])

b = a>2
print(b)

c= np.where(a>2, a, 999)

print(c)


[False False  True  True  True]
[999 999   3   4   5]


In [70]:
#isnan 

a= np.array([1, np.nan, 3, np.nan])
result = np.isnan(a)
print(result)

[False  True False  True]


In [72]:
import numpy as np

# Creating a 3x3 random matrix
arr = np.random.randint(1, 10, (3, 3))
print("Original Array:\n", arr)

# Indexing and Slicing
print("First Row:\n", arr[0])
print("Last Column:\n", arr[:, -1])
print("Middle Element:\n", arr[1, 1])

# Reshaping
arr_1d = arr.reshape(9)
arr_2d = arr.reshape(3, -1)
arr_3d = arr.reshape(3, 3, 1)
print("Reshaped 1D:\n", arr_1d)
print("Reshaped 2D:\n", arr_2d)
print("Reshaped 3D:\n", arr_3d)

# Element-wise Operations
arr_add = arr + 2
arr_sub = arr - 2
arr_mul = arr * 2
arr_div = arr / 2
arr_pow = arr ** 2
print("Addition:\n", arr_add)
print("Subtraction:\n", arr_sub)
print("Multiplication:\n", arr_mul)
print("Division:\n", arr_div)
print("Power:\n", arr_pow)

# Statistical Functions
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
var = np.var(arr)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", var)

# Sorting
arr_sorted = np.sort(arr, axis=None)
print("Sorted Array:\n", arr_sorted)

# Other Functions
arr_sum = np.sum(arr)
arr_prod = np.prod(arr)
arr_min = np.min(arr)
arr_max = np.max(arr)
print("Sum:", arr_sum)
print("Product:", arr_prod)
print("Minimum Value:", arr_min)
print("Maximum Value:", arr_max)


Original Array:
 [[4 9 7]
 [9 7 1]
 [2 5 7]]
First Row:
 [4 9 7]
Last Column:
 [7 1 7]
Middle Element:
 7
Reshaped 1D:
 [4 9 7 9 7 1 2 5 7]
Reshaped 2D:
 [[4 9 7]
 [9 7 1]
 [2 5 7]]
Reshaped 3D:
 [[[4]
  [9]
  [7]]

 [[9]
  [7]
  [1]]

 [[2]
  [5]
  [7]]]
Addition:
 [[ 6 11  9]
 [11  9  3]
 [ 4  7  9]]
Subtraction:
 [[ 2  7  5]
 [ 7  5 -1]
 [ 0  3  5]]
Multiplication:
 [[ 8 18 14]
 [18 14  2]
 [ 4 10 14]]
Division:
 [[2.  4.5 3.5]
 [4.5 3.5 0.5]
 [1.  2.5 3.5]]
Power:
 [[16 81 49]
 [81 49  1]
 [ 4 25 49]]
Mean: 5.666666666666667
Median: 7.0
Standard Deviation: 2.70801280154532
Variance: 7.333333333333333
Sorted Array:
 [1 2 4 5 7 7 7 9 9]
Sum: 51
Product: 1111320
Minimum Value: 1
Maximum Value: 9


In [73]:
pip install pillow

Note: you may need to restart the kernel to use updated packages.Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   --------- ------------------------------ 0.6/2.6 MB 12.6 MB/s eta 0:00:01
   -------------------------------- ------- 2.1/2.6 MB 22.5 MB/s eta 0:00:01
   ---------------------------------------  2.6/2.6 MB 27.8 MB/s eta 0:00:01
   ---------------------------------------  2.6/2.6 MB 27.8 MB/s eta 0:00:01
   ---------------------------------------- 2.6/2.6 MB 13.9 MB/s eta 0:00:00




[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [75]:
from PIL import Image
from numpy import asarray

#load the image
img = Image.open('sample.png')

numpydata = asarray(img)

print(type(numpydata))

print(numpydata.shape)

print(numpydata)



<class 'numpy.ndarray'>
(922, 1758, 4)
[[[ 24  24  24 255]
  [ 24  24  24 255]
  [ 24  24  24 255]
  ...
  [ 24  24  24 255]
  [ 24  24  24 255]
  [ 24  24  24 255]]

 [[ 24  24  24 255]
  [ 24  24  24 255]
  [ 24  24  24 255]
  ...
  [ 24  24  24 255]
  [ 24  24  24 255]
  [ 24  24  24 255]]

 [[ 24  24  24 255]
  [ 24  24  24 255]
  [ 24  24  24 255]
  ...
  [ 24  24  24 255]
  [ 24  24  24 255]
  [ 24  24  24 255]]

 ...

 [[ 35  24  24 255]
  [ 24  24  24 255]
  [ 24  24  24 255]
  ...
  [ 31  31  31 255]
  [ 31  31  31 255]
  [ 31  31  31 255]]

 [[175 133  82 255]
  [ 35  24  24 255]
  [ 24  24  24 255]
  ...
  [ 31  31  31 255]
  [ 31  31  31 255]
  [ 31  31  31 255]]

 [[175 198 198 255]
  [175 133  82 255]
  [ 35  24  24 255]
  ...
  [ 31  31  31 255]
  [ 31  31  31 255]
  [ 31  31  31 255]]]


In [79]:
#write a numpy program to test whether none of the elements of a given array are zero

array = np.array([1, 2, 3, 0, 5, 6])
print(array.all())

False


In [82]:

#write a numpy program to test whether none of the elements of a given array are non -zero
array = np.array([1, 2, 0, 4, 5, 6])
print(array.any())

True


In [84]:
#write a numpy program to test whether none of the elements-wise positive or negative infinity


array = np.array([1, 2, np.inf, 4, 5, 6, -np.inf])


if not np.any(np.isinf(array)):
    print("None ")
else:
    print("positive or negative infinity elements in array.")


positive or negative infinity elements in array.


In [86]:
##write a numpy program to test whether none of the elements-wise for NaN of given array

a= np.array([1, np.nan, 3, np.nan])
result = np.isnan(a)
print(result)


[False  True False  True]


In [87]:
##write a numpy program to create a 3*4 matrix filled with values from 10 to 21

x= np.random.randint(10,21,size=[3,2])
print(x)

[[11 16]
 [14 15]
 [14 12]]


In [94]:
##write a numpy program to create a 10 * 10 matrix, in which the element on the border will be equal to 1 and inside 0

a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [95]:
#pandas for data manipulation
#working with single column data is pandas series
#working with  row and column -> Dataframe

import pandas as pd



In [96]:
ser1 = pd.Series([1,2,3,4], index = ['USA', 'GERMANY', 'JAPAN', 'UK'])
print(ser1)

USA        1
GERMANY    2
JAPAN      3
UK         4
dtype: int64


In [97]:
ser2 = pd.Series([1,2,3,4], index = ['USA', 'GERMANY', 'JAPAN', 'ITALY'])
print(ser2)

USA        1
GERMANY    2
JAPAN      3
ITALY      4
dtype: int64


In [98]:
ser1['UK']

np.int64(4)

In [5]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [110]:
#import io
data = pd.read_excel('Book1.xlsx')
print(data.head())

  Unnamed: 0     City Country  Maths  Science
0       John   Mumbai   India     42        6
1      Alice   London      UK     44       77
2        Bob   London      UK     43       59
3       Mary  Florida     USA     26       49
4        Dan   Madrid   Spain     82       58


In [ ]:
#remove unamed: 0
df =pd.read_excel("Book1.xlsx", index_col=0)
print(df)

          City Country  Maths  Science
John    Mumbai   India     42        6
Alice   London      UK     44       77
Bob     London      UK     43       59
Mary   Florida     USA     26       49
Dan     Madrid   Spain     82       58


In [ ]:
#need specific column
df =pd.read_excel("Book1.xlsx", index_col=0, usecols="A:C")
print(df)

          City Country
John    Mumbai   India
Alice   London      UK
Bob     London      UK
Mary   Florida     USA
Dan     Madrid   Spain


In [116]:
#name column
df =pd.read_excel("Book1.xlsx", index_col=0, usecols="A:C",names=['Name','City','Country'])
print(df)

          City Country
Name                  
John    Mumbai   India
Alice   London      UK
Bob     London      UK
Mary   Florida     USA
Dan     Madrid   Spain


In [117]:
#skipping column

df =pd.read_excel("Book1.xlsx", index_col=0, usecols=[0,2,4])
print(df)

      Country  Science
John    India        6
Alice      UK       77
Bob        UK       59
Mary      USA       49
Dan     Spain       58


In [119]:
df =pd.read_excel("Book1.xlsx", index_col=0, usecols=[0,4])
print(df)

       Science
John         6
Alice       77
Bob         59
Mary        49
Dan         58


In [122]:
df =pd.read_excel("Book1.xlsx", index_col=0, usecols=[2])
print(df)

Empty DataFrame
Columns: []
Index: [India, UK, UK, USA, Spain]


In [123]:
#sheet navigation (dont know sheet name)
df =pd.read_excel("Book1.xlsx", index_col=0, sheet_name=1)
print(df)


                   City    Country Degree    Depart
Manish           Mumbai      India    MSC     Maths
M Chowdry         Delhi      India    B.A   Physics
A chow            Perth  Austraila    PHD     Maths
David           Colombo   Srilanka    BBM  Pharmacy
Samyual Hriody  Newyork        USA   B.sc  Medicine


In [125]:
#sheet navigation ( know sheet name)
df =pd.read_excel("Book1.xlsx", index_col=0, sheet_name='student')
print(df)


          City Country  Maths  Science
John    Mumbai   India     42        6
Alice   London      UK     44       77
Bob     London      UK     43       59
Mary   Florida     USA     26       49
Dan     Madrid   Spain     82       58


In [7]:
import pandas as pd
df=pd.read_excel("Book1.xlsx",index_col=0,sheet_name='teacher')
print(df)


                   City    Country Degree    Depart
Manish           Mumbai      India    MSC     Maths
M Chowdry         Delhi      India    B.A   Physics
A chow            Perth  Austraila    PHD     Maths
David           Colombo   Srilanka    BBM  Pharmacy
Samyual Hriody  Newyork        USA   B.sc  Medicine


In [10]:
import pandas as pd
df.describe()

City Country Degree Depart
count        5       5      5      5
unique       5       4      5      4
top     Mumbai   India    MSC  Maths
freq         1       2      1      2

In [11]:
df.to_csv('Naveen.csv')

In [34]:
df=pd.read_excel("SampleData.xlsx")
print(df)

         Country   Age   Salary Purchased
0          India  25.0  50000.0       Yes
1            USA  30.0  60000.0        No
2             UK   NaN  55000.0       Yes
3         Canada  35.0      NaN        No
4      Australia  28.0  70000.0       Yes
5        Germany  33.0  62000.0        No
6         France  24.0  58000.0       Yes
7         Brazil  29.0  54000.0        No
8          Japan  31.0  63000.0       Yes
9          China  27.0  71000.0        No
10   South Korea  26.0      NaN       Yes
11  South Africa   NaN  68000.0        No
12        Russia  34.0  64000.0       Yes
13         Italy  23.0      NaN        No
14        Mexico  36.0  66000.0       Yes


In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    15 non-null     object 
 1   Age        13 non-null     float64
 2   Salary     12 non-null     float64
 3   Purchased  15 non-null     object 
dtypes: float64(2), object(2)
memory usage: 612.0+ bytes


In [36]:
#5 point summry
df.describe()

Age        Salary
count  13.000000     12.000000
mean   29.307692  61750.000000
std     4.289223   6593.729804
min    23.000000  50000.000000
25%    26.000000  57250.000000
50%    29.000000  62500.000000
75%    33.000000  66500.000000
max    36.000000  71000.000000

In [28]:
m = df['Age'].mean()
print(m)


29.307692307692307


In [37]:
print(df[4:8])

     Country   Age   Salary Purchased
4  Australia  28.0  70000.0       Yes
5    Germany  33.0  62000.0        No
6     France  24.0  58000.0       Yes
7     Brazil  29.0  54000.0        No


In [38]:
print(df.iloc[4:6])

     Country   Age   Salary Purchased
4  Australia  28.0  70000.0       Yes
5    Germany  33.0  62000.0        No


In [39]:
print(df['Country'][4])

Australia


In [42]:

df = df.drop('Country',axis=1)
print(df)

         Country   Age   Salary Purchased
0          India  25.0  50000.0       Yes
1            USA  30.0  60000.0        No
2             UK   NaN  55000.0       Yes
3         Canada  35.0      NaN        No
4      Australia  28.0  70000.0       Yes
5        Germany  33.0  62000.0        No
6         France  24.0  58000.0       Yes
7         Brazil  29.0  54000.0        No
8          Japan  31.0  63000.0       Yes
9          China  27.0  71000.0        No
10   South Korea  26.0      NaN       Yes
11  South Africa   NaN  68000.0        No
12        Russia  34.0  64000.0       Yes
13         Italy  23.0      NaN        No
14        Mexico  36.0  66000.0       Yes
     Age   Salary Purchased
0   25.0  50000.0       Yes
1   30.0  60000.0        No
2    NaN  55000.0       Yes
3   35.0      NaN        No
4   28.0  70000.0       Yes
5   33.0  62000.0        No
6   24.0  58000.0       Yes
7   29.0  54000.0        No
8   31.0  63000.0       Yes
9   27.0  71000.0        No
10  26.0      NaN   

In [43]:
df['Country'] = ['India', 'USA', 'UK', 'Canada', 'Australia', 'Germany', 'France', 'Brazil', 'Japan', 'China', 'South Korea', 'South Africa', 'Russia', 'Italy', 'Mexico']

In [47]:
print(df)

     Age   Salary Purchased       Country     Area
0   25.0  50000.0       Yes         India  chennai
1   30.0  60000.0        No           USA   guindy
2    NaN  55000.0       Yes            UK    Porur
3   35.0      NaN        No        Canada  chennai
4   28.0  70000.0       Yes     Australia   guindy
5   33.0  62000.0        No       Germany    Porur
6   24.0  58000.0       Yes        France  chennai
7   29.0  54000.0        No        Brazil   guindy
8   31.0  63000.0       Yes         Japan    Porur
9   27.0  71000.0        No         China  chennai
10  26.0      NaN       Yes   South Korea   guindy
11   NaN  68000.0        No  South Africa    Porur
12  34.0  64000.0       Yes        Russia  chennai
13  23.0      NaN        No         Italy   guindy
14  36.0  66000.0       Yes        Mexico    Porur


In [46]:
df['Area'] = ['chennai', 'guindy', 'Porur'] * 5 

In [49]:
df = df.drop(3)
print(df)

     Age   Salary Purchased       Country     Area
0   25.0  50000.0       Yes         India  chennai
1   30.0  60000.0        No           USA   guindy
2    NaN  55000.0       Yes            UK    Porur
4   28.0  70000.0       Yes     Australia   guindy
5   33.0  62000.0        No       Germany    Porur
6   24.0  58000.0       Yes        France  chennai
7   29.0  54000.0        No        Brazil   guindy
8   31.0  63000.0       Yes         Japan    Porur
9   27.0  71000.0        No         China  chennai
10  26.0      NaN       Yes   South Korea   guindy
11   NaN  68000.0        No  South Africa    Porur
12  34.0  64000.0       Yes        Russia  chennai
13  23.0      NaN        No         Italy   guindy
14  36.0  66000.0       Yes        Mexico    Porur


In [52]:
df1 = df.sort_values(by='Salary', ascending=True)
print(df1)

     Age   Salary Purchased       Country     Area
0   25.0  50000.0       Yes         India  chennai
7   29.0  54000.0        No        Brazil   guindy
2    NaN  55000.0       Yes            UK    Porur
6   24.0  58000.0       Yes        France  chennai
1   30.0  60000.0        No           USA   guindy
5   33.0  62000.0        No       Germany    Porur
8   31.0  63000.0       Yes         Japan    Porur
12  34.0  64000.0       Yes        Russia  chennai
14  36.0  66000.0       Yes        Mexico    Porur
11   NaN  68000.0        No  South Africa    Porur
4   28.0  70000.0       Yes     Australia   guindy
9   27.0  71000.0        No         China  chennai
10  26.0      NaN       Yes   South Korea   guindy
13  23.0      NaN        No         Italy   guindy


In [56]:
#conditon

print(df)
df.loc[df['Age']>48, 'Salary']=0
print(df)

     Age   Salary Purchased       Country     Area
0   25.0  50000.0       Yes         India  chennai
1   30.0  60000.0        No           USA   guindy
2    NaN  55000.0       Yes            UK    Porur
4   28.0  70000.0       Yes     Australia   guindy
5   33.0  62000.0        No       Germany    Porur
6   24.0      0.0       Yes        France  chennai
7   29.0  54000.0        No        Brazil   guindy
8   31.0  63000.0       Yes         Japan    Porur
9   27.0  71000.0        No         China  chennai
10  26.0      NaN       Yes   South Korea   guindy
11   NaN  68000.0        No  South Africa    Porur
12  34.0  64000.0       Yes        Russia  chennai
13  23.0      NaN        No         Italy   guindy
14  36.0  66000.0       Yes        Mexico    Porur
     Age   Salary Purchased       Country     Area
0   25.0  50000.0       Yes         India  chennai
1   30.0  60000.0        No           USA   guindy
2    NaN  55000.0       Yes            UK    Porur
4   28.0  70000.0       Yes    

In [57]:
print(df)
df.loc[((df['Age']<40) & (df['Country'] == 'France')), 'Salary'] = 0
print(df)

     Age   Salary Purchased       Country     Area
0   25.0  50000.0       Yes         India  chennai
1   30.0  60000.0        No           USA   guindy
2    NaN  55000.0       Yes            UK    Porur
4   28.0  70000.0       Yes     Australia   guindy
5   33.0  62000.0        No       Germany    Porur
6   24.0      0.0       Yes        France  chennai
7   29.0  54000.0        No        Brazil   guindy
8   31.0  63000.0       Yes         Japan    Porur
9   27.0  71000.0        No         China  chennai
10  26.0      NaN       Yes   South Korea   guindy
11   NaN  68000.0        No  South Africa    Porur
12  34.0  64000.0       Yes        Russia  chennai
13  23.0      NaN        No         Italy   guindy
14  36.0  66000.0       Yes        Mexico    Porur
     Age   Salary Purchased       Country     Area
0   25.0  50000.0       Yes         India  chennai
1   30.0  60000.0        No           USA   guindy
2    NaN  55000.0       Yes            UK    Porur
4   28.0  70000.0       Yes    

In [59]:
print(df)
df.loc[((df['Age']<40) & (df['Country'] == 'India')), 'Salary'] = 0
print(df)

     Age   Salary Purchased       Country     Area
0   25.0      0.0       Yes         India  chennai
1   30.0  60000.0        No           USA   guindy
2    NaN  55000.0       Yes            UK    Porur
4   28.0  70000.0       Yes     Australia   guindy
5   33.0  62000.0        No       Germany    Porur
6   24.0      0.0       Yes        France  chennai
7   29.0  54000.0        No        Brazil   guindy
8   31.0  63000.0       Yes         Japan    Porur
9   27.0  71000.0        No         China  chennai
10  26.0      NaN       Yes   South Korea   guindy
11   NaN  68000.0        No  South Africa    Porur
12  34.0  64000.0       Yes        Russia  chennai
13  23.0      NaN        No         Italy   guindy
14  36.0  66000.0       Yes        Mexico    Porur
     Age   Salary Purchased       Country     Area
0   25.0      0.0       Yes         India  chennai
1   30.0  60000.0        No           USA   guindy
2    NaN  55000.0       Yes            UK    Porur
4   28.0  70000.0       Yes    

In [60]:
#CREATE ANY CSV DATA, READ JSON, read CSV

df = pd.read_csv('test1.csv')
print(df)

      name branch  year  cgpa
0   nikhil    coe     2   9.0
1  sanchit     it     3   9.8


In [61]:
df = pd.read_json('data1.json')
print(df)

ValueError: If using all scalar values, you must pass an index